#+TITLE: PNSAC Newsletter January 2016

* Northstar Chronicle contents for January 2016 [4/8]

  - [ ] Editor's Notes: =To be sent once I have all the other
   articles.=
  - [ ] Message from the Director General CASM. =He is supposed to get
   it to me this week.=
  - [ ] Notes from the President. =Richard is supposed to get it to me this
   week.=
  - [X] Project Manager's Report.  =I will forward Bruce's email with his
   report as an attachment.= [[/Users/drew/Development/gitrepos/latex/pnsac/newsletter/resources/Project Manager Progress Report 2015.doc][report]]
  - [X] Our Members: =This is a new feature in an interview format with a
   different member each issue, starting with Bruce Gemmill. Bruce's
   interview is attached to another email message from him that I will
   forward to you.  There should be a introduction which will read as
   follows (I suggest it be done in a different font or using
   italics)=

    Introduction: Bruce Gemmill has been involved with Project North Star
    since 2005 and has exceeded 9,000 volunteer hours. Bruce is presently
    the Project Manager, as well as a member of the board of
    directors..

    [[/Users/drew/Development/gitrepos/latex/pnsac/newsletter/resources/Personal Interview - Gemmill.doc][interview]]

  - [X]  "Volunteers Working on North Star."  =This is an article from
    Legion Magazine and I have attached a copy of same.= [[/Users/drew/Development/gitrepos/latex/pnsac/newsletter/resources/NSVolunteers-Canvet.pdf][article]]
  - [ ] Calendar of Events:  =I am working on this.=
  - [X] Contact Information: =Essentially the same as the last edition.=
